apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: up-domain-secret
spec:
  secretName: up-domain-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: "*.up.reix.tech"
  dnsNames:
    - "*.up.reix.tech"
